Update SwingWindSound.cs
bit of refactor (might be related to an audio error occuring in webgl builds? Fix not tested)
<i>Autoconnected Player "Autoconnected Player"</i> ./Modules/Audio/Public/AudioSource.cpp(1574) : Error executing dspHead->setRelativeAudibility(relativeAudibility) (An invalid object handle was used. )